apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
  annotations:
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "partner", "product_id": "ace-mp", "partner_name": "Partner"}'
spec:
  descriptor:
    type: ace-mp
    version: '0.20241118.0'
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  addOwnerRef: true
  componentKinds:
  - group: batch
    kind: Job
  - group: ""
    kind: Pod
  - group: ""
    kind: Service
  - group: apps
    kind: DaemonSet
  - group: apps
    kind: StatefulSet
  - group: cacerts.csi.cert-manager.io
    kind: CAProviderClass
  - group: ""
    kind: ServiceAccount
  - group: rbac.authorization.k8s.io
    kind: Role
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
