apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ace-mp.fullname" . }}-checker
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ace-mp.fullname" . }}-checker
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ace-mp.fullname" . }}-checker
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ace-mp.fullname" . }}-checker
subjects:
  - kind: ServiceAccount
    name: {{ include "ace-mp.fullname" . }}-checker
    namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ace-mp.fullname" . }}-checker
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  template:
    spec:
      serviceAccountName: {{ include "ace-mp.fullname" . }}-checker
      containers:
      - name: checker
        image: {{ .Values.tester.image }}
        command:
        - /bin/sh
        - -c
        - |-
          set -x
          kubectl wait --for=create pod/ace-platform-api-0-x-ace-x-{{ .Release.Name }} --timeout=15m
          kubectl wait --for=condition=Ready pod/ace-platform-api-0-x-ace-x-{{ .Release.Name }} --timeout=15m
          echo "api pod running!"
          while ! curl -k -s "https://ace-ingress-x-ace-x-{{ .Release.Name }}" > /dev/null; do
            echo "Request failed, retrying in 5 seconds..."
            sleep 5
          done
          echo "Test successful!"
      restartPolicy: Never
