properties:
  name:
    default: ace-mp
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    default: ace
    type: string
    x-google-marketplace:
      type: NAMESPACE
  installerURL:
    type: string
    default: https://appscode.com/links/installer/332800/tamal-gcp-mp/cs68ln0r266s739nfl50-4ld8gh48cw/archive.tar.gz
