apiVersion: v2
name: ace-mp
description: Helm chart to install ACE as a Kubernetes App
type: application
version: v2024.10.17
appVersion: v2024.10.17
dependencies:
- name: cert-manager-csi-driver-cacerts
  repository: oci://ghcr.io/appscode-charts
  condition: cert-manager-csi-driver-cacerts.enabled
  version: v2024.7.28
- name: vcluster
  repository: oci://ghcr.io/appscode-charts
  version: 0.20.0
