nameOverride: ""
fullnameOverride: ""

cert-manager-csi-driver-cacerts:
  enabled: true

vcluster:
  enabled: true
  fallbackHostDns: false
  # # https://www.vcluster.com/docs/v0.19/o11y/metrics/metrics_server_proxy#enabling-the-metrics-server-proxy-recommended
  # proxy:
  #   metricsServer:
  #     nodes:
  #       enabled: true
  #     pods:
  #       enabled: true
  sync:
    # https://www.vcluster.com/docs/v0.19/o11y/metrics/metrics_server
    nodes:
      enabled: true
    hoststorageclasses:
      enabled: true
  syncer:
    resources:
      limits:
        ephemeral-storage: 8Gi
        memory: 8Gi
      requests:
        ephemeral-storage: 1Gi
        cpu: 200m
        memory: 3.5Gi
  telemetry:
    disabled: true
